
services:
  nest-admin-server:
    build: .
    container_name: nest-admin-server
    pull_policy: always
    restart: always
    command: [ "pm2-runtime", "ecosystem.config.js" ]
    env_file:
      - .env
      - .env.production
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - nest_admin_net

networks:
  nest_admin_net:
    driver: bridge

