services:
  mysql_water:
    image: mysql:latest
    container_name: mysql-water-dev
    restart: always
    env_file:
      - .env
      - .env.development
    ports:
      - '${DB_PORT:-3304}:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置utf8字符集
    volumes:
      - ./__data/mysql/:/var/lib/mysql/ # ./__data/mysql/ 路径可以替换成自己的路径
      - ./deploy/sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本，若 ./__data/mysql/ 文件夹存在数据，则不会执行初始化脚本
    networks:
      - nest_admin_net

  redis_water:
    image: redis:alpine
    container_name: radis-water-dev
    restart: always
    env_file:
      - .env
      - .env.development
    ports:
      - '${REDIS_PORT:-6378}:6379'
    command: >
      --requirepass ${REDIS_PASSWORD:-123456}
    networks:
      - nest_admin_net

  # end_water:
  #   build: .
  #   container_name: nest_admin_end_water
  #   restart: always
  #   env_file:
  #     - .env
  #     - .env.development
  #   ports:
  #     - '${APP_PORT}:3000'
  #   # command: [ "pm2", "start", "ecosystem.config.js" ]
  #   command: ENTRYPOINT ["sh", "-c", "./wait-for \"$DB_HOST:$DB_PORT\" -- && exec \"$@\"", "--"]
  #   networks:
  #     - nest_admin_net
  #   depends_on:
  #     - redis_water
  #     - mysql_water

networks:
  nest_admin_net:
    driver: bridge
