services:


  app:
    build: .
    container_name: nest-water-prod
    restart: always
    ports:
      - "7001:7001"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PROJECT_DIR= ${PROJECT_DIR}
    command: >
      sh -c "
      pnpm migration:run &&
      pm2-runtime ecosystem.config.js
      "
    depends_on:
      - mysql1
      - redis1
    networks:
      - nest_prod_net

  mysql1:
    image: mysql:latest
    container_name: nest-water-mysql
    restart: always
    env_file:
      - .env
      - .env.production
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置utf8字符集
    volumes:
      - ./__data/mysql/:/var/lib/mysql/ # ./__data/mysql/ 路径可以替换成自己的路径
      - ./deploy/sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本，若 ./__data/mysql/ 文件夹存在数据，则不会执行初始化脚本
    networks:
      - nest_prod_net

  redis1:
    image: redis:alpine
    container_name: nest-water-redis
    restart: always
    env_file:
      - .env
      - .env.production
    ports:
      - '${REDIS_PORT}:6379'
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - nest_prod_net
networks:
  nest_prod_net:
    name: nest_prod_net
